# Generated by Django 5.1.4 on 2025-01-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_login_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=60)),
                ('district', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=60)),
            ],
        ),
    ]
