# Generated by Django 5.1.4 on 2025-01-16 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='login_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.login'),
            preserve_default=False,
        ),
    ]
