# Generated by Django 5.1.4 on 2025-02-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_station_login_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='usertype',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
