# Generated by Django 5.1.4 on 2025-02-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_advertisement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='media',
            field=models.FileField(upload_to=''),
        ),
    ]
