# Generated by Django 5.1.4 on 2025-02-07 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_advertisement_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='station_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.station'),
        ),
    ]
