# Generated by Django 5.1.4 on 2025-02-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_slotbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotbooking',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
