# Generated by Django 5.1.4 on 2025-02-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_slotbooking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotbooking',
            name='date',
            field=models.DateField(),
        ),
    ]
