# Generated by Django 5.1.4 on 2025-02-13 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_slotbooking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotbooking',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.login'),
        ),
    ]
