# Generated by Django 5.1.4 on 2025-02-13 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_slotbooking_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slotbooking',
            old_name='station_id',
            new_name='login_id',
        ),
    ]
