# Generated by Django 5.1.4 on 2025-02-14 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_station_id_slotbooking_login_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='slotbooking',
        ),
    ]
