# Generated by Django 5.1.4 on 2025-02-14 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_slotbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotbooking',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_login', to='app.station'),
        ),
    ]
