# Generated by Django 5.1.4 on 2025-02-14 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_slotbooking_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotbooking',
            name='login_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.login'),
        ),
        migrations.AlterField(
            model_name='slotbooking',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.station'),
        ),
    ]
