# Generated by Django 5.1.4 on 2025-02-20 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_slotbooking_login_id_alter_slotbooking_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='slotbooking',
        ),
    ]
