# Generated by Django 5.1.6 on 2025-02-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_slotbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotbooking',
            name='cancel_status',
            field=models.IntegerField(default=0),
        ),
    ]
