# Generated by Django 5.1.6 on 2025-03-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_complaints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='complaint',
            field=models.TextField(max_length=100),
        ),
    ]
