# Generated by Django 5.1.6 on 2025-03-15 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_complaints_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaints',
            old_name='user_id',
            new_name='user_logid',
        ),
    ]
