# Generated by Django 5.1.6 on 2025-03-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_rename_user_id_complaints_user_logid'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='reply',
            field=models.CharField(max_length=106, null=True),
        ),
    ]
