# Generated by Django 5.1.6 on 2025-04-06 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_complaints_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardownername', models.CharField(max_length=25)),
                ('cardno', models.CharField(max_length=15)),
                ('cvv', models.CharField(max_length=5)),
                ('expmonth', models.IntegerField()),
                ('expyear', models.IntegerField()),
                ('amount', models.IntegerField(default=0)),
                ('current_date', models.DateTimeField(auto_now_add=True)),
                ('bookingid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.slotbooking')),
                ('login_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
