# Generated by Django 5.1.6 on 2025-04-06 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='expmonth',
            new_name='expmonth_year',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='expyear',
        ),
    ]
