# Generated by Django 5.1.6 on 2025-04-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_rename_expmonth_payment_expmonth_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='fare',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
